spring:
  application:
    name: holywave
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_RESOURCE_SERVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  datasource:
    #url: jdbc:postgresql://postgres:5432/holywave
    #username: ${POSTGRES_USERNAME}
    #password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    context-path: /api/v1
  shutdown: graceful

management:
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development. set it to 0.1 for prod
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/logs

logging:
  level:
    root: INFO
    org.softsystem: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: INFO
    org.springframework.boot.docker.compose: INFO

cloudinary:
  folder: event_posts